[General]
SyntaxVersion=2
BeginHotkey=9
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=03ee46d4-b13e-4fb6-91c2-c8963d976100
Description=下跳
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
'==========以下是按键精灵录制的内容==========
Delay 100
KeyDown "Down", 1
Delay 96
KeyDown "Space", 1
Delay 88
KeyUp "Space", 1
Delay 16
KeyUp "Down", 1
'==========以上是按键精灵录制的内容==========
